spring:
  data:
    mongodb:
      authentication-database : ${MONGO_DATABASE}
      username : ${MONGO_USERNAME}
      password : ${MONGO_PASSWORD}
      database : ${MONGO_DATABASE}
      port : ${MONGO_PORT}
      host : localhost